Laboratorio 1

1.1
```{r}
Student_1 <- c(50.4,62.3,92.1,77.6,TRUE)
Student_2 <- c(41.7,87.9,75.3,72.4,FALSE)
Student_3 <- c(30.3,67.8,69.3,71.2,FALSE)
Student_4 <- c(65.4,85.1,92.3,96.8,TRUE)
Student_5 <- c(70.4,88.2,95.2,90.7,TRUE)
```

1.2
```{r}
students_vector <- c(Student_1,Student_2,Student_3,Student_4,Student_5)
students_vector
```

1.3
```{r}
students_matrix <- matrix(students_vector, byrow=TRUE, nrow=5)
students_matrix
```

2.1
```{r}
name_students = c("Lily Brown", "Davis Moore", "Susan Taylor", "Mike Jones", "Tom Hill" )

name_courses_legal_age = c( "TIC", "Accounting", "Psychology", "Ethics",
"Legal_age" )
```

2.2
```{r}
colnames(students_matrix) <- name_courses_legal_age
rownames(students_matrix) <- name_students
students_matrix
```

3.1
```{r}
total_grade_student = rowSums(students_matrix[ , 1:4])
total_grade_student
```

3.2
```{r}
result_students = cbind(students_matrix, total_grade_student )
result_students
```

4.1
```{r}
selected_elements = result_students[c(1,3,5),c(2,4)]
selected_elements
```

5.1
```{r}
students_grades_df = data.frame(result_students)
students_grades_df
```

5.2
```{r}
subset(students_grades_df, Accounting>80 & Legal_age == TRUE)
```

6
```{r}
 students_projection <- function(i,j)
   for (i in 1:nrows(result_students)){
     for(j in 1:ncol(result_students[,1:4])){
     }
}
```


6.2
```{r}
for (n in students_projection) {
  if (n>=61){
    print("Student approved")
  } 
  else if (n>=45){
    print("Student may be approved")
  } 
  else{
    print("Student at risk")
  }
}

#Esta parte es la que me esta dando error y sale 
#Error in for (n in students_projection) { : invalid for() loop sequence

```

6.3
```{r}
students_projection
```



7.1 
```{r}
index_education <- function(grande){
  ((1+(grande/100))/2)
}
```

7.2
```{r}
  all_students_grade=students_grades_df[ , 1:4]
all_students_grade
```

7.3
```{r}
Result <- lapply(all_students_grade, index_education)
Result
```

8 
```{r}
score_mean <- colMeans(students_grades_df[ , 1:4])
score_mean
```

